/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Suhendra
 */
public class CRent extends javax.swing.JFrame {
    public double total, lama, harga;
    /**
     * Creates new form CRent
     */
    public CRent() {
        initComponents();
    }
    public CRent(String penyewa, String no_hp,String kendaraan, String lama_sewa, double harga) {
        initComponents();
        jLpenyewa.setText(penyewa.toString());
        jLnohp.setText(no_hp.toString());
        jLkendraan.setText(kendaraan.toString());
        jLlama.setText(lama_sewa + " Hari ");
        jLbiaya.setText("Rp. " + String.valueOf(harga) + " / Hari");

        total = (Double.valueOf(lama_sewa) * harga ) + 100000;
        jLtotal.setText(String.valueOf(total));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCars = new javax.swing.JLabel();
        jLMotor = new javax.swing.JLabel();
        jLLogout = new javax.swing.JLabel();
        jBtnCancel = new javax.swing.JButton();
        jBtnNext = new javax.swing.JButton();
        jLpenyewa = new javax.swing.JLabel();
        jLnohp = new javax.swing.JLabel();
        jLkendraan = new javax.swing.JLabel();
        jLlama = new javax.swing.JLabel();
        jLbiaya = new javax.swing.JLabel();
        jLAsuransi = new javax.swing.JLabel();
        jLtotal = new javax.swing.JLabel();
        carbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setResizable(false);
        getContentPane().setLayout(null);

        jLCars.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLCars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCars.setText("Cars");
        jLCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCarsMouseClicked(evt);
            }
        });
        getContentPane().add(jLCars);
        jLCars.setBounds(950, 50, 70, 30);

        jLMotor.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLMotor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMotor.setText("Motorcycles");
        jLMotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMotorMouseClicked(evt);
            }
        });
        getContentPane().add(jLMotor);
        jLMotor.setBounds(1060, 50, 160, 30);

        jLLogout.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLLogout.setForeground(new java.awt.Color(255, 0, 51));
        jLLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLogout.setText("Logout");
        jLLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(jLLogout);
        jLLogout.setBounds(1270, 50, 100, 30);

        jBtnCancel.setBackground(new java.awt.Color(31, 69, 144));
        jBtnCancel.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jBtnCancel.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCancel.setText("Cancel");
        jBtnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCancelMouseClicked(evt);
            }
        });
        getContentPane().add(jBtnCancel);
        jBtnCancel.setBounds(950, 770, 210, 80);

        jBtnNext.setBackground(new java.awt.Color(31, 69, 144));
        jBtnNext.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jBtnNext.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNext.setText("Rent Now");
        jBtnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnNextMouseClicked(evt);
            }
        });
        getContentPane().add(jBtnNext);
        jBtnNext.setBounds(1170, 770, 230, 80);

        jLpenyewa.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLpenyewa.setText("Nama");
        getContentPane().add(jLpenyewa);
        jLpenyewa.setBounds(1120, 240, 550, 30);

        jLnohp.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLnohp.setText("no hp");
        getContentPane().add(jLnohp);
        jLnohp.setBounds(1120, 300, 550, 30);

        jLkendraan.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLkendraan.setText("mobil");
        getContentPane().add(jLkendraan);
        jLkendraan.setBounds(1120, 370, 550, 30);

        jLlama.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLlama.setText("lama");
        getContentPane().add(jLlama);
        jLlama.setBounds(1120, 430, 90, 30);

        jLbiaya.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLbiaya.setText("Rp. 999");
        getContentPane().add(jLbiaya);
        jLbiaya.setBounds(1120, 520, 550, 30);

        jLAsuransi.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLAsuransi.setText("Rp. 100.000");
        getContentPane().add(jLAsuransi);
        jLAsuransi.setBounds(1120, 610, 160, 30);

        jLtotal.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLtotal.setText("Rp. 9999");
        getContentPane().add(jLtotal);
        jLtotal.setBounds(1120, 690, 550, 30);

        carbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/confirm rent page.png"))); // NOI18N
        getContentPane().add(carbg);
        carbg.setBounds(0, 0, 1440, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCarsMouseClicked
        // TODO add your handling code here:
        Mobil mobil = new Mobil();
        mobil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLCarsMouseClicked

    private void jLMotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMotorMouseClicked
        // TODO add your handling code here:
        Motor motor = new Motor();
        motor.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLMotorMouseClicked

    private void jLLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogoutMouseClicked
        // TODO add your handling code here:
        Login masuk = new Login();
        masuk.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLLogoutMouseClicked

    private void jBtnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelMouseClicked
        // TODO add your handling code here:
        Mobil mobil = new Mobil();
        mobil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnCancelMouseClicked

    private void jBtnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNextMouseClicked
        // TODO add your handling code here:
        success berhasil = new success();
        berhasil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnNextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carbg;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnNext;
    private javax.swing.JLabel jLAsuransi;
    private javax.swing.JLabel jLCars;
    private javax.swing.JLabel jLLogout;
    private javax.swing.JLabel jLMotor;
    private javax.swing.JLabel jLbiaya;
    private javax.swing.JLabel jLkendraan;
    private javax.swing.JLabel jLlama;
    private javax.swing.JLabel jLnohp;
    private javax.swing.JLabel jLpenyewa;
    private javax.swing.JLabel jLtotal;
    // End of variables declaration//GEN-END:variables
}
