/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Suhendra
 */
import Classes.*;
public class Mobil extends javax.swing.JFrame {
    public String nama;
    public String transmisi;
    public String bbm;
    public double harga;
    /**
     * Creates new form Mobil
     */
    public Mobil() {
        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLCars = new javax.swing.JLabel();
        jLMotor = new javax.swing.JLabel();
        jLLogout = new javax.swing.JLabel();
        jLMobil1 = new javax.swing.JLabel();
        jLHarga1 = new javax.swing.JLabel();
        jLTransmisi1 = new javax.swing.JLabel();
        jLBbm1 = new javax.swing.JLabel();
        jBtnRent1 = new javax.swing.JButton();
        jLMobil2 = new javax.swing.JLabel();
        jLHarga2 = new javax.swing.JLabel();
        jLTransmisi2 = new javax.swing.JLabel();
        jLBbm2 = new javax.swing.JLabel();
        jBtnRent2 = new javax.swing.JButton();
        jLMobil3 = new javax.swing.JLabel();
        jLHarga3 = new javax.swing.JLabel();
        jLTransmisi3 = new javax.swing.JLabel();
        jLBbm3 = new javax.swing.JLabel();
        jBtnRent3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        carbg = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cars");
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLCars.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLCars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCars.setText("Cars");
        getContentPane().add(jLCars);
        jLCars.setBounds(950, 50, 70, 30);

        jLMotor.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLMotor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMotor.setText("Motorcycles");
        jLMotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMotorMouseClicked(evt);
            }
        });
        getContentPane().add(jLMotor);
        jLMotor.setBounds(1060, 50, 160, 30);

        jLLogout.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLLogout.setForeground(new java.awt.Color(255, 0, 51));
        jLLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLogout.setText("Logout");
        jLLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(jLLogout);
        jLLogout.setBounds(1270, 50, 100, 30);

        jLMobil1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLMobil1.setText("Avanza");
        getContentPane().add(jLMobil1);
        jLMobil1.setBounds(100, 520, 100, 30);

        jLHarga1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLHarga1.setText("Rp. 100.000/Hari");
        getContentPane().add(jLHarga1);
        jLHarga1.setBounds(140, 560, 156, 30);

        jLTransmisi1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLTransmisi1.setText("Manual");
        getContentPane().add(jLTransmisi1);
        jLTransmisi1.setBounds(140, 614, 70, 20);

        jLBbm1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLBbm1.setText("Pertamax");
        getContentPane().add(jLBbm1);
        jLBbm1.setBounds(140, 660, 90, 30);

        jBtnRent1.setBackground(new java.awt.Color(31, 69, 144));
        jBtnRent1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jBtnRent1.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRent1.setText("Rent Now");
        jBtnRent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRent1MouseClicked(evt);
            }
        });
        jBtnRent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRent1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnRent1);
        jBtnRent1.setBounds(100, 730, 180, 60);

        jLMobil2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLMobil2.setText("Jazz");
        getContentPane().add(jLMobil2);
        jLMobil2.setBounds(550, 520, 100, 30);

        jLHarga2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLHarga2.setText("Rp. 150.000/Hari");
        getContentPane().add(jLHarga2);
        jLHarga2.setBounds(590, 560, 156, 30);

        jLTransmisi2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLTransmisi2.setText("Automatic");
        getContentPane().add(jLTransmisi2);
        jLTransmisi2.setBounds(590, 614, 100, 20);

        jLBbm2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLBbm2.setText("Pertamax");
        getContentPane().add(jLBbm2);
        jLBbm2.setBounds(590, 660, 90, 30);

        jBtnRent2.setBackground(new java.awt.Color(31, 69, 144));
        jBtnRent2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jBtnRent2.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRent2.setText("Rent Now");
        jBtnRent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRent2MouseClicked(evt);
            }
        });
        getContentPane().add(jBtnRent2);
        jBtnRent2.setBounds(550, 730, 180, 60);

        jLMobil3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLMobil3.setText("Pajero");
        getContentPane().add(jLMobil3);
        jLMobil3.setBounds(990, 520, 100, 30);

        jLHarga3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLHarga3.setText("Rp. 200.000/Hari");
        getContentPane().add(jLHarga3);
        jLHarga3.setBounds(1030, 560, 156, 30);

        jLTransmisi3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLTransmisi3.setText("Manual");
        getContentPane().add(jLTransmisi3);
        jLTransmisi3.setBounds(1030, 614, 70, 20);

        jLBbm3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLBbm3.setText("Pertamax");
        getContentPane().add(jLBbm3);
        jLBbm3.setBounds(1030, 660, 90, 30);

        jBtnRent3.setBackground(new java.awt.Color(31, 69, 144));
        jBtnRent3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jBtnRent3.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRent3.setText("Rent Now");
        jBtnRent3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRent3MouseClicked(evt);
            }
        });
        jBtnRent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRent3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnRent3);
        jBtnRent3.setBounds(990, 730, 180, 60);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("MPV");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(870, 520, 40, 20);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("MPV");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1310, 520, 40, 20);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("MPV");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(414, 520, 40, 20);

        carbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/car page.png"))); // NOI18N
        getContentPane().add(carbg);
        carbg.setBounds(0, 0, 1440, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLMotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMotorMouseClicked
        // TODO add your handling code here:
        Motor motor = new Motor();
        motor.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLMotorMouseClicked

    private void jLLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogoutMouseClicked
        // TODO add your handling code here:
        Login masuk = new Login();
        masuk.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLLogoutMouseClicked

    private void jBtnRent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRent1MouseClicked
        // TODO add your handling code here:
        Car mobil1 = new Car("Avanza", "MPV");
        mobil1.setHarga(100000);
        mobil1.setTipeBbm("Pertamax");
        mobil1.setTransmisi("Manual");
        nama = mobil1.getNama();
        transmisi = mobil1.getTransmisi();
        harga = mobil1.getHarga();
        bbm = mobil1.getTipebbm();
        Rent rental = new Rent(nama.toString(), transmisi.toString(), bbm.toString(), harga);
        rental.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jBtnRent1MouseClicked

    private void jBtnRent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRent1ActionPerformed

    private void jBtnRent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRent3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRent3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jBtnRent2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRent2MouseClicked
        // TODO add your handling code here:
        Car mobil2 = new Car("Jazz", "MPV");
        mobil2.setHarga(150000);
        mobil2.setTipeBbm("Pertamax");
        mobil2.setTransmisi("Automatic");
        nama = mobil2.getNama();
        transmisi = mobil2.getTransmisi();
        harga = mobil2.getHarga();
        bbm = mobil2.getTipebbm();
        Rent rental = new Rent(nama.toString(), transmisi.toString(), bbm.toString(), harga);
        rental.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnRent2MouseClicked

    private void jBtnRent3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRent3MouseClicked
        // TODO add your handling code here:
        Car mobil3 = new Car("Jazz", "MPV");
        mobil3.setHarga(200000);
        mobil3.setTipeBbm("Pertamax");
        mobil3.setTransmisi("Manual");
        nama = mobil3.getNama();
        transmisi = mobil3.getTransmisi();
        harga = mobil3.getHarga();
        bbm = mobil3.getTipebbm();
        Rent rental = new Rent(nama.toString(), transmisi.toString(), bbm.toString(), harga);
        rental.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnRent3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carbg;
    private javax.swing.JButton jBtnRent1;
    private javax.swing.JButton jBtnRent2;
    private javax.swing.JButton jBtnRent3;
    private javax.swing.JLabel jLBbm1;
    private javax.swing.JLabel jLBbm2;
    private javax.swing.JLabel jLBbm3;
    private javax.swing.JLabel jLCars;
    private javax.swing.JLabel jLHarga1;
    private javax.swing.JLabel jLHarga2;
    private javax.swing.JLabel jLHarga3;
    private javax.swing.JLabel jLLogout;
    private javax.swing.JLabel jLMobil1;
    private javax.swing.JLabel jLMobil2;
    private javax.swing.JLabel jLMobil3;
    private javax.swing.JLabel jLMotor;
    private javax.swing.JLabel jLTransmisi1;
    private javax.swing.JLabel jLTransmisi2;
    private javax.swing.JLabel jLTransmisi3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
