/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Suhendra
 */
public class Rent extends javax.swing.JFrame {
    public double harga;
    /**
     * Creates new form Rent
     */
    public Rent() {
        initComponents();
    }

    public Rent(String nama, String transmisi, String bbm, double harga) {
        initComponents();
        jTkendaraan.setText(nama);
        jTtransmisi.setText(transmisi);
        jTtipebbm.setText(bbm);
        this.harga = harga;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCars = new javax.swing.JLabel();
        jLMotor = new javax.swing.JLabel();
        jLLogout = new javax.swing.JLabel();
        jBtnCancel = new javax.swing.JButton();
        jBtnNext = new javax.swing.JButton();
        jTpenyewa = new javax.swing.JTextField();
        jTnohp = new javax.swing.JTextField();
        jTlamasewa = new javax.swing.JTextField();
        jTkendaraan = new javax.swing.JTextField();
        jTtransmisi = new javax.swing.JTextField();
        jTtipebbm = new javax.swing.JTextField();
        carbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLCars.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLCars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCars.setText("Cars");
        jLCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCarsMouseClicked(evt);
            }
        });
        getContentPane().add(jLCars);
        jLCars.setBounds(950, 50, 70, 30);

        jLMotor.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLMotor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMotor.setText("Motorcycles");
        jLMotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMotorMouseClicked(evt);
            }
        });
        getContentPane().add(jLMotor);
        jLMotor.setBounds(1060, 50, 160, 30);

        jLLogout.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLLogout.setForeground(new java.awt.Color(255, 0, 51));
        jLLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLogout.setText("Logout");
        jLLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(jLLogout);
        jLLogout.setBounds(1270, 50, 100, 30);

        jBtnCancel.setBackground(new java.awt.Color(31, 69, 144));
        jBtnCancel.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jBtnCancel.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCancel.setText("Cancel");
        jBtnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCancelMouseClicked(evt);
            }
        });
        getContentPane().add(jBtnCancel);
        jBtnCancel.setBounds(950, 770, 210, 80);

        jBtnNext.setBackground(new java.awt.Color(31, 69, 144));
        jBtnNext.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jBtnNext.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNext.setText("Next");
        jBtnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnNextMouseClicked(evt);
            }
        });
        getContentPane().add(jBtnNext);
        jBtnNext.setBounds(1170, 770, 220, 80);

        jTpenyewa.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTpenyewa.setToolTipText("");
        getContentPane().add(jTpenyewa);
        jTpenyewa.setBounds(730, 240, 660, 50);

        jTnohp.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTnohp.setToolTipText("");
        getContentPane().add(jTnohp);
        jTnohp.setBounds(730, 320, 660, 50);

        jTlamasewa.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTlamasewa.setToolTipText("");
        getContentPane().add(jTlamasewa);
        jTlamasewa.setBounds(730, 420, 660, 50);

        jTkendaraan.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTkendaraan.setToolTipText("");
        jTkendaraan.setEnabled(false);
        getContentPane().add(jTkendaraan);
        jTkendaraan.setBounds(730, 520, 660, 50);

        jTtransmisi.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTtransmisi.setToolTipText("");
        jTtransmisi.setEnabled(false);
        getContentPane().add(jTtransmisi);
        jTtransmisi.setBounds(730, 610, 660, 50);

        jTtipebbm.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTtipebbm.setToolTipText("");
        jTtipebbm.setEnabled(false);
        getContentPane().add(jTtipebbm);
        jTtipebbm.setBounds(730, 700, 660, 50);

        carbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/rent.png"))); // NOI18N
        getContentPane().add(carbg);
        carbg.setBounds(0, 0, 1440, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLMotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMotorMouseClicked
        // TODO add your handling code here:
        Motor motor = new Motor();
        motor.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLMotorMouseClicked

    private void jLLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogoutMouseClicked
        // TODO add your handling code here:
        Login masuk = new Login();
        masuk.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLLogoutMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jLCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCarsMouseClicked
        // TODO add your handling code here:
        Mobil mobil = new Mobil();
        mobil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLCarsMouseClicked

    private void jBtnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelMouseClicked
        // TODO add your handling code here:
        Mobil mobil = new Mobil();
        mobil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnCancelMouseClicked

    private void jBtnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNextMouseClicked
        // TODO add your handling code here:
        CRent confirm = new CRent(jTpenyewa.getText().toString(), jTnohp.getText().toString(), jTkendaraan.getText().toString(), jTlamasewa.getText().toString(), harga);
        confirm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnNextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carbg;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnNext;
    private javax.swing.JLabel jLCars;
    private javax.swing.JLabel jLLogout;
    private javax.swing.JLabel jLMotor;
    private javax.swing.JTextField jTkendaraan;
    private javax.swing.JTextField jTlamasewa;
    private javax.swing.JTextField jTnohp;
    private javax.swing.JTextField jTpenyewa;
    private javax.swing.JTextField jTtipebbm;
    private javax.swing.JTextField jTtransmisi;
    // End of variables declaration//GEN-END:variables
}
